apiVersion: v1
kind: Service
metadata:
  labels:
    run: sar2html
  name: sar2html-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: sar2html
  type: NodePort
