#!/bin/bash

#########################################################################
#                                                                       #
# SAR2HTML 3.2.1                                                        #
#                                                                       #
# Written by Cem TAN                                               	#
# Mail address: tan.cem@gmail.com                                       #
#                                                                       #
#                                                                       #
# SAR based performance reporting tool. It produces html file and       #
# graphics in png format under plot directory                           #
#                                                                       #
#########################################################################

# OS DEPENDENT SAR PARAMETERS ------------------------------------------------------------ START
################################################################################################

# REDHAT 3--------------------------------------------------------------------------------------
SA_Redhat_3='b B c d I_SUM n_DEV n_EDEV n_SOCK P_ALL q r R v w W y'
SA_Redhat_3_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Redhat_3_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS'
SA_Redhat_3_c='proc/s,1 2 3,PROCESS CREATION ACTIVITY'
SA_Redhat_3_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w'
SA_Redhat_3_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Redhat_3_n_DEV='rxbyt/s txbyt/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Redhat_3_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Redhat_3_n_SOCK='totsck tcpsck udpsck rawsck ip-frag,1 2 3 4 5 6 7,NETWORK SOCKET STATISTICS'
SA_Redhat_3_P_ALL='%user %nice %system %iowait %idle,1 2 4 5 6 7 8,PROCESSOR ACTIVITY'
SA_Redhat_3_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Redhat_3_r='kbmemfree kbmemused kbbuffers kbcached,1 2 3 4 6 7,MEMORY UTILIZATION:kbswpfree kbswpused kbswpcad,1 2 8 9 11,SWAP UTILIZATION:%memused %swpused,1 2 5 10,MEMORY AND SWAP %'
SA_Redhat_3_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Redhat_3_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-sz,1 2 4,USED FILE HANDLES:inode-sz,1 2 5,USED INODE HANDLERS:super-sz,1 2 6,SUPER BLOCK HANDLERS:dquot-sz,1 2 8,ALLOCATED DISK QUOTA ENTRIES:rtsig-sz,1 2 10,QUEUED RT SIGNALS:%super-sz %dquot-sz %rtsig-sz,1 2 7 9 11,KERNEL TABLES %'
SA_Redhat_3_w='cswch/s,1 2 3,SYSTEM SWITCHING ACTIVITY'
SA_Redhat_3_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Redhat_3_y='rcvin/s xmtin/s,1 2 3 4,TTY DEVICE ACTIVITY'
SA_Redhat_3_SPECIAL='d n_DEV n_EDEV P_ALL'

# REDHAT 4--------------------------------------------------------------------------------------
SA_Redhat_4='b B c d I_SUM n_DEV n_EDEV n_SOCK P_ALL q r R v w W y'
SA_Redhat_4_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Redhat_4_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS'
SA_Redhat_4_c='proc/s,1 2 3,PROCESS CREATION ACTIVITY'
SA_Redhat_4_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w'
SA_Redhat_4_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Redhat_4_n_DEV='rxbyt/s txbyt/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Redhat_4_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Redhat_4_n_SOCK='totsck tcpsck udpsck rawsck ip-frag,1 2 3 4 5 6 7,NETWORK SOCKET STATISTICS'
SA_Redhat_4_P_ALL='%user %nice %system %iowait %idle,1 2 4 5 6 7 8,PROCESSOR ACTIVITY'
SA_Redhat_4_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Redhat_4_r='kbmemfree kbmemused kbbuffers kbcached,1 2 3 5 6 7,MEMORY UTILIZATION:kbswpfree kbswpused kbswpcad,1 2 8 9 11,SWAP UTILIZATION:%memused %swpused,1 2 5 10,MEMORY AND SWAP %'
SA_Redhat_4_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Redhat_4_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-sz,1 2 4,USED FILE HANDLES:inode-sz,1 2 5,USED INODE HANDLERS:super-sz,1 2 6,SUPER BLOCK HANDLERS:dquot-sz,1 2 8,ALLOCATED DISK QUOTA ENTRIES:rtsig-sz,1 2 10,QUEUED RT SIGNALS:%super-sz %dquot-sz %rtsig-sz,1 2 7 9 11,KERNEL TABLES %'
SA_Redhat_4_w='cswch/s,1 2 3,SYSTEM SWITCHING ACTIVITY'
SA_Redhat_4_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Redhat_4_y='rcvin/s xmtin/s,1 2 3 4,TTY DEVICE ACTIVITY'
SA_Redhat_4_SPECIAL='d n_DEV n_EDEV P_ALL'

# REDHAT 5--------------------------------------------------------------------------------------
SA_Redhat_5='b B c d I_SUM n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r R v w W y'
SA_Redhat_5_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Redhat_5_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS'
SA_Redhat_5_c='proc/s,1 2 3,PROCESS CREATION ACTIVITY'
SA_Redhat_5_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w:avgrq-sz avgqu-sz,1 2 7 8,I/O REQUESTS AND QUEUE LENGHT:await,1 2 9,AVEARGE WAIT TIME,svctm,1 2 10,AVERAGE SERVICE TIME:%util,1 2 11,CPU PERCENTAGE of I/O'
SA_Redhat_5_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Redhat_5_n_DEV='rxbyt/s txbyt/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Redhat_5_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Redhat_5_n_NFS='read/s write/s,1 2 5 6,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 4 7 8,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Redhat_5_n_NFSD='sread/s swrite/s,1 2 10 11,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 4 12 13,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 2 5 6 7,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 2 8 9,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Redhat_5_n_SOCK='totsck tcpsck udpsck rawsck ip-frag,1 2 3 4 5 6 7,NETWORK SOCKET STATISTICS'
SA_Redhat_5_P_ALL='%user %nice %system %iowait %steal %idle,1 2 4 5 6 7 8 9,PROCESSOR ACTIVITY'
SA_Redhat_5_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Redhat_5_r='kbmemfree kbmemused kbbuffers kbcached,1 2 3 4 6 7,MEMORY UTILIZATION:kbswpfree kbswpused kbswpcad,1 2 8 9 11,SWAP UTILIZATION:%memused %swpused,1 2 5 10,MEMORY AND SWAP %'
SA_Redhat_5_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Redhat_5_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-sz,1 2 4,USED FILE HANDLES:inode-sz,1 2 5,USED INODE HANDLERS:super-sz,1 2 6,SUPER BLOCK HANDLERS:dquot-sz,1 2 8,ALLOCATED DISK QUOTA ENTRIES:rtsig-sz,1 2 10,QUEUED RT SIGNALS:%super-sz %dquot-sz %rtsig-sz,1 2 7 9 11,KERNEL TABLES %'
SA_Redhat_5_w='cswch/s,1 2 3,SYSTEM SWITCHING ACTIVITY'
SA_Redhat_5_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Redhat_5_y='rcvin/s xmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_Redhat_5_SPECIAL='d n_DEV n_EDEV P_ALL'

# REDHAT 6---------------------------------------------------------------------------------------
SA_Redhat_6='b B d I_SUM n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r R S v w W y'
SA_Redhat_6_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Redhat_6_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS:pgfree/s pgscank/s pgscand/s pgsteal/s,1 2 7 8 9 10,PAGE OPERATIONS:%vmeff,1 2 11,EFFICIENCY OF PAGE RECLAIM'
SA_Redhat_6_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w:avgrq-sz avgqu-sz,1 2 7 8,I/O REQUESTS AND QUEUE LENGHT:await,1 2 9,AVEARGE WAIT TIME,svctm,1 2 10,AVERAGE SERVICE TIME:%util,1 2 11,CPU PERCENTAGE of I/O'
SA_Redhat_6_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Redhat_6_n_DEV='rxkB/s txkB/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Redhat_6_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Redhat_6_n_NFS='read/s write/s,1 2 5 6,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 4 7 8,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Redhat_6_n_NFSD='sread/s swrite/s,1 2 10 11,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 4 12 13,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 2 5 6 7,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 2 8 9,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Redhat_6_n_SOCK='totsck tcpsck udpsck rawsck ip-frag tcp-tw,1 2 3 4 5 6 7 8,NETWORK SOCKET STATISTICS'
SA_Redhat_6_P_ALL='%user %nice %system %iowait %steal %idle,1 2 4 5 6 7 8 9,PROCESSOR ACTIVITY'
SA_Redhat_6_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Redhat_6_r='kbmemfree kbmemused kbbuffers kbcached kbcommit,1 2 3 4 6 7 8,MEMORY UTILIZATION:%memused %commit,1 2 5 9,MEMORY UTILIZATION %'
SA_Redhat_6_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Redhat_6_S='kbswpfree kbswpused kbswpcad,1 2 3 4 6,SWAP UTILIZATION:%swpused %swpcad,1 2 5 7,SWAP UTILIZATION %'
SA_Redhat_6_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-nr inode-nr,1 2 4 5,NUMBER OF FILE AND INODE HANDLERS:pty-nr,1 2 6,NUMBER OF PSEUDO-TERMINALS'
SA_Redhat_6_w='proc/s,1 2 3,PROCESS CREATION ACTIVITY:cswch/s,1 2 4,SYSTEM SWITCHING ACTIVITY'
SA_Redhat_6_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Redhat_6_y='rcvin/s xmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_Redhat_6_SPECIAL='d n_DEV n_EDEV P_ALL'

# REDHAT 7---------------------------------------------------------------------------------------
SA_Redhat_7='b B d n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r R H S v w W y'
SA_Redhat_7_b='tps rtps wtps,1 2 3 4 5,I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Redhat_7_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS:pgfree/s pgscank/s pgscand/s pgsteal/s,1 2 7 8 9 10,PAGE OPERATIONS:%vmeff,1 2 11,EFFICIENCY OF PAGE RECLAIM'
SA_Redhat_7_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w:avgrq-sz avgqu-sz,1 2 7 8,I/O REQUESTS AND QUEUE LENGHT:await,1 2 9,AVEARGE WAIT TIME,svctm,1 2 10,AVERAGE SERVICE TIME:%util,1 2 11,CPU PERCENTAGE of I/O'
SA_Redhat_7_H='kbhugfree kbhugused,1 2 3 4,HUGEPAGE UTILIZATION:%hugused,1 2 5,HUGEPAGE UTILIZATION %'
SA_Redhat_7_n_DEV='rxkB/s txkB/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Redhat_7_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Redhat_7_n_NFS='read/s write/s,1 2 5 6,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 4 7 8,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Redhat_7_n_NFSD='sread/s swrite/s,1 2 10 11,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 4 12 13,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 2 5 6 7,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 2 8 9,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Redhat_7_n_SOCK='totsck tcpsck udpsck rawsck ip-frag tcp-tw,1 2 3 4 5 6 7 8,NETWORK SOCKET STATISTICS'
SA_Redhat_7_P_ALL='%user %sys %idle,1 2 4 6 13,PROCESSOR ACTIVITY:%nice %iowait %steal %irq %soft %guest %gnice,1 2 5 7 8 9 10 11 12,PROCESSOR ACTIVITY DETAILS'
SA_Redhat_7_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:blocked,1 2 8,NUMBER OF BLOCKED PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Redhat_7_r='kbmemfree kbmemused kbbuffers kbcached kbcommit,1 2 3 4 6 7 8,MEMORY UTILIZATION:kbactive kbinact kbdirty,1 2 10 11 12,MEMORY UTILIZATION DETAILS:%memused %commit,1 2 5 9,MEMORY UTILIZATION %'
SA_Redhat_7_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Redhat_7_S='kbswpfree kbswpused kbswpcad,1 2 3 4 6,SWAP UTILIZATION:%swpused %swpcad,1 2 5 7,SWAP UTILIZATION %'
SA_Redhat_7_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-nr inode-nr,1 2 4 5,NUMBER OF FILE AND INODE HANDLERS:pty-nr,1 2 6,NUMBER OF PSEUDO-TERMINALS'
SA_Redhat_7_w='proc/s,1 2 3,PROCESS CREATION ACTIVITY:cswch/s,1 2 4,SYSTEM SWITCHING ACTIVITY'
SA_Redhat_7_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Redhat_7_y='rcvin/s xmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_Redhat_7_SPECIAL='d n_DEV n_EDEV P_ALL'

# SUSE 8----------------------------------------------------------------------------------------
SA_Suse_8='b B c d I_SUM n_DEV n_EDEV n_SOCK U_ALL q r R v w W y'
SA_Suse_8_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Suse_8_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:activepg inadtypg inaclnpg inatarpg,1 2 5 6 7 8,PAGE STATISTICS'
SA_Suse_8_c='proc/s,1 2 3,PROCESS CREATION ACTIVITY'
SA_Suse_8_d='tps,1 2 4,NUMBER OF TRANSFERS:blks/s,1 2 5,NUMBER OF TRANSFERRED BLOCKS'
SA_Suse_8_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Suse_8_n_DEV='rxbyt/s txbyt/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Suse_8_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Suse_8_n_SOCK='totsck tcpsck udpsck rawsck ip-frag,1 2 3 4 5 6 7,NETWORK SOCKET STATISTICS'
SA_Suse_8_U_ALL='%user %nice %system %idle,1 2 4 5 6 7,PROCESSOR ACTIVITY'
SA_Suse_8_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5,1 2 5 6,LOAD AVERAGE'
SA_Suse_8_r='kbmemfree kbmemused kbmemshrd kbbuffers kbcached,1 2 3 4 6 7 8,MEMORY UTILIZATION:kbswpfree kbswpused,1 2 9 10,SWAP UTILIZATION:%memused %swpused,1 2 5 11,MEMORY AND SWAP %'
SA_Suse_8_R='frmpg/s bufpg/s shmpg/s campg/s,1 2 3 4 5 6,MEMORY STATISTICS'
SA_Suse_8_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-sz,1 2 4,USED FILE HANDLES:inode-sz,1 2 6,USED INODE HANDLERS:super-sz,1 2 7,SUPER BLOCK HANDLERS:dquot-sz,1 2 9,ALLOCATED DISK QUOTA ENTRIES:rtsig-sz,1 2 11,QUEUED RT SIGNALS:%file-sz %super-sz %dquot-sz %rtsig-sz,1 2 5 8 10 12,KERNEL TABLES %'
SA_Suse_8_w='cswch/s,1 2 3,SYSTEM SWITCHING ACTIVITY'
SA_Suse_8_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Suse_8_y='rcvin/s xmtin/s,1 2 3 4,TTY DEVICE ACTIVITY'
SA_Suse_8_SPECIAL='d n_DEV n_EDEV U_ALL'

# SUSE 9----------------------------------------------------------------------------------------
SA_Suse_9='b B c d I_SUM n_DEV n_EDEV n_SOCK P_ALL q r R v w W y'
SA_Suse_9_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Suse_9_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS'
SA_Suse_9_c='proc/s,1 2 3,PROCESS CREATION ACTIVITY'
SA_Suse_9_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w'
SA_Suse_9_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Suse_9_n_DEV='rxbyt/s txbyt/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Suse_9_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Suse_9_n_SOCK='totsck tcpsck udpsck rawsck ip-frag,1 2 3 4 5 6 7,NETWORK SOCKET STATISTICS'
SA_Suse_9_P_ALL='%user %nice %system %iowait %idle,1 2 4 5 6 7 8,PROCESSOR ACTIVITY'
SA_Suse_9_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Suse_9_r='kbmemfree kbmemused kbbuffers kbcached,1 2 3  4 6 7,MEMORY UTILIZATION:kbswpfree kbswpused kbswpcad,1 2 8 9 11,SWAP UTILIZATION:%memused %swpused,1 2 5 10,MEMORY AND SWAP %'
SA_Suse_9_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Suse_9_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-sz,1 2 4,USED FILE HANDLES:inode-sz,1 2 5,USED INODE HANDLERS:super-sz,1 2 6,SUPER BLOCK HANDLERS:dquot-sz,1 2 8,ALLOCATED DISK QUOTA ENTRIES:rtsig-sz,1 2 10,QUEUED RT SIGNALS:%super-sz %dquot-sz %rtsig-sz,1 2 7 9 11,KERNEL TABLES %'
SA_Suse_9_w='cswch/s,1 2 3,SYSTEM SWITCHING ACTIVITY'
SA_Suse_9_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Suse_9_y='rcvin/s xmtin/s,1 2 3 4,TTY DEVICE ACTIVITY'
SA_Suse_9_SPECIAL='d n_DEV n_EDEV P_ALL'

# SUSE 10---------------------------------------------------------------------------------------
SA_Suse_10='b B c d I_SUM n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r R v w W y'
SA_Suse_10_b='tps rtps wtps,1 2 3 4, I/O TRANSACTION:bread/s bwrtn/s,1 5 6,I/O TRANSFER RATE'
SA_Suse_10_B='pgpgin/s pgpgout/s,1 2 3,PAGING STATISTICS:fault/s majflt/s,1 4 5,PAGE FAULTS:pgfree/s pgscank/s pgscand/s pgsteal/s,1 6 7 8 9,PAGE OPERATIONS:%vmeff,1 10,EFFICIENCY OF PAGE RECLAIM'
SA_Suse_10_c='proc/s,1 2,PROCESS CREATION ACTIVITY'
SA_Suse_10_d='tps,1 3,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 4 5,NUMBER OF SECTOR r/w:avgrq-sz avgqu-sz,1 6 7,I/O REQUESTS AND QUEUE LENGHT:await,1 8,AVEARGE WAIT TIME,svctm,1 9,AVERAGE SERVICE TIME:%util,1 10,CPU PERCENTAGE of I/O'
SA_Suse_10_I_SUM='intr/s,1 3,INTERRUPT ACTIVITY'
SA_Suse_10_n_DEV='rxkB/s txkB/s,1 5 6,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 3 4 7 8 9,NETWORK STATISTICS'
SA_Suse_10_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 3 4 5 6 7 8 9 10 11,NETWORK ERROR STATISTICS'
SA_Suse_10_n_NFS='read/s write/s,1 4 5,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 6 7,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Suse_10_n_NFSD='sread/s swrite/s,1 9 10,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 11 12,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 4 5 6,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 7 8,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Suse_10_n_SOCK='totsck tcpsck udpsck rawsck ip-frag tcp-tw,1 2 3 4 5 6 7,NETWORK SOCKET STATISTICS'
SA_Suse_10_P_ALL='%user %nice %system %iowait %steal %idle,1 3 4 5 6 7 8,PROCESSOR ACTIVITY'
SA_Suse_10_q='runq-sz,1 2,QUEUE LENGTH:plist-sz,1 3,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 4 5 6,LOAD AVERAGE'
SA_Suse_10_r='kbmemfree kbmemused kbbuffers kbcached,1 2 3 5 6,MEMORY UTILIZATION:kbswpfree kbswpused kbswpcad,1 7 8 10,SWAP UTILIZATION:%memused %swpused,1 4 9,MEMORY AND SWAP %'
SA_Suse_10_R='frmpg/s bufpg/s campg/s,1 2 3 4,MEMORY STATISTICS'
SA_Suse_10_v='dentunusd,1 2,UNUSED CACHE ENTRIES:file-nr inode-nr,1 3 4,NUMBER OF FILE AND INODE HANDLERS:pty-nr,1 5,NUMBER OF PSEUDO-TERMINALS'
SA_Suse_10_w='cswch/s,1 2,SYSTEM SWITCHING ACTIVITY'
SA_Suse_10_W='pswpin/s pswpout/s,1 2 3,SWAPPING STATISTICS'
SA_Suse_10_y='rcvin/s xmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 3 4 5 6 7,TTY DEVICE ACTIVITY'
SA_Suse_10_SPECIAL='d n_DEV n_EDEV P_ALL'

# SUSE 11---------------------------------------------------------------------------------------
SA_Suse_11='b B d I_SUM n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r R S v w W y'
SA_Suse_11_b='tps rtps wtps,1 2 3 4 5, I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Suse_11_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS:pgfree/s pgscank/s pgscand/s pgsteal/s,1 2 7 8 9 10,PAGE OPERATIONS:%vmeff,1 2 11,EFFICIENCY OF PAGE RECLAIM'
SA_Suse_11_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w:avgrq-sz avgqu-sz,1 2 7 8,I/O REQUESTS AND QUEUE LENGHT:await,1 2 9,AVEARGE WAIT TIME,svctm,1 2 10,AVERAGE SERVICE TIME:%util,1 2 11,CPU PERCENTAGE of I/O'
SA_Suse_11_I_SUM='intr/s,1 2 4,INTERRUPT ACTIVITY'
SA_Suse_11_n_DEV='rxkB/s txkB/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS'
SA_Suse_11_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Suse_11_n_NFS='read/s write/s,1 2 5 6,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 4 7 8,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Suse_11_n_NFSD='sread/s swrite/s,1 2 10 11,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 4 12 13,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 2 5 6 7,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 2 8 9,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Suse_11_n_SOCK='totsck tcpsck udpsck rawsck ip-frag tcp-tw,1 2 3 4 5 6 7 8,NETWORK SOCKET STATISTICS'
SA_Suse_11_P_ALL='%user %nice %system %iowait %steal %idle,1 2 4 5 6 7 8 9,PROCESSOR ACTIVITY'
SA_Suse_11_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Suse_11_r='kbmemfree kbmemused kbbuffers kbcached kbcommit,1 2 3 4 6 7 8,MEMORY UTILIZATION:%memused %commit,1 2 5 9,MEMORY UTILIZATION %'
SA_Suse_11_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Suse_11_S='kbswpfree kbswpused kbswpcad,1 2 3 4 6,SWAP UTILIZATION:%swpused %swpcad,1 2 5 7,SWAP UTILIZATION %'
SA_Suse_11_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-nr inode-nr,1 2 4 5,NUMBER OF FILE AND INODE HANDLERS:pty-nr,1 2 6,NUMBER OF PSEUDO-TERMINALS'
SA_Suse_11_w='proc/s,1 2 3,PROCESS CREATION ACTIVITY:cswch/s,1 2 4,SYSTEM SWITCHING ACTIVITY'
SA_Suse_11_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Suse_11_y='rcvin/s xmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_Suse_11_SPECIAL='d n_DEV n_EDEV P_ALL'

# SUSE 12----------------------------------------------------------------------------------------
SA_Suse_12='b B d n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r R H S v w W y'
SA_Suse_12_b='tps rtps wtps,1 2 3 4 5,I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Suse_12_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS:pgfree/s pgscank/s pgscand/s pgsteal/s,1 2 7 8 9 10,PAGE OPERATIONS:%vmeff,1 2 11,EFFICIENCY OF PAGE RECLAIM'
SA_Suse_12_d='tps,1 2 4,NUMBER OF TRANSFERS:rd_sec/s wr_sec/s,1 2 5 6,NUMBER OF SECTOR r/w:avgrq-sz avgqu-sz,1 2 7 8,I/O REQUESTS AND QUEUE LENGHT:await,1 2 9,AVEARGE WAIT TIME,svctm,1 2 10,AVERAGE SERVICE TIME:%util,1 2 11,CPU PERCENTAGE of I/O'
SA_Suse_12_H='kbhugfree kbhugused,1 2 3 4,HUGEPAGE UTILIZATION:%hugused,1 2 5,HUGEPAGE UTILIZATION %'
SA_Suse_12_n_DEV='rxkB/s txkB/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS:%ifutil,1 2 11,NETWORK UTILIZATION %'
SA_Suse_12_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Suse_12_n_NFS='read/s write/s,1 2 5 6,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 4 7 8,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Suse_12_n_NFSD='sread/s swrite/s,1 2 10 11,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 4 12 13,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 2 5 6 7,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 2 8 9,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Suse_12_n_SOCK='totsck tcpsck udpsck rawsck ip-frag tcp-tw,1 2 3 4 5 6 7 8,NETWORK SOCKET STATISTICS'
SA_Suse_12_P_ALL='%user %sys %idle,1 2 4 6 13,PROCESSOR ACTIVITY:%nice %iowait %steal %irq %soft %guest %gnice,1 2 5 7 8 9 10 11 12,PROCESSOR ACTIVITY DETAILS'
SA_Suse_12_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:blocked,1 2 8,NUMBER OF BLOCKED PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Suse_12_r='kbmemfree kbmemused kbbuffers kbcached kbcommit,1 2 3 4 6 7 8,MEMORY UTILIZATION:kbactive kbinact kbdirty,1 2 10 11 12,MEMORY UTILIZATION DETAILS:%memused %commit,1 2 5 9,MEMORY UTILIZATION %'
SA_Suse_12_R='frmpg/s bufpg/s campg/s,1 2 3 4 5,MEMORY STATISTICS'
SA_Suse_12_S='kbswpfree kbswpused kbswpcad,1 2 3 4 6,SWAP UTILIZATION:%swpused %swpcad,1 2 5 7,SWAP UTILIZATION %'
SA_Suse_12_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-nr inode-nr,1 2 4 5,NUMBER OF FILE AND INODE HANDLERS:pty-nr,1 2 6,NUMBER OF PSEUDO-TERMINALS'
SA_Suse_12_w='proc/s,1 2 3,PROCESS CREATION ACTIVITY:cswch/s,1 2 4,SYSTEM SWITCHING ACTIVITY'
SA_Suse_12_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Suse_12_y='rcvin/s xmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_Suse_12_SPECIAL='d n_DEV n_EDEV P_ALL'

# HP-UX 11.11-----------------------------------------------------------------------------------
SA_HPUX_11='a b c d Sm Mq Mu v w y'
SA_HPUX_11_a='iget/s namei/s dirbk/s,1 2 3 4 5,USE OF FILE ACCESS SYSTEM ROUTINES'
SA_HPUX_11_b='bread/s bwrit/s lread/s lwrit/s pread/s pwrit/s,1 2 3 4 5 6 9 10,BUFFER ACTIVITY PART 1:%rcache %wcache,1 2 7 8,BUFFER ACTIVITY PART 2'
SA_HPUX_11_c='rchar/s wchar/s,1 2 8 9,NUMBER OF CHARACTERS TRANSFERRED BY R/W SYSTEM CALLS:scall/s,1 2 3,NUMBER OF SYSTEM CALLS:sread/s swrit/s fork/s exec/s,1 2 4 5 6 7,R/W FORK AND EXEC SYSTEM CALLS'
SA_HPUX_11_d='r+w/s blks/s,1 2 6 7,NUMBER OF TRANSFERS:avque,1 2 5,NUMBER OF REQUESTS:avwait avserv,1 2 8 9,SERVICE AND WAIT TIMEi:%busy,1 2 4,BUSY TIME'
SA_HPUX_11_Sm='msg/s sema/s select/s,1 2 3 4 5,NUMBER OF SYSTEM V CALLS'
SA_HPUX_11_Mq='runq-sz swpq-sz,1 2 4 6,RUN AND SWAP QUEUE:%runocc %swpocc,1 2 5 7,RUN AND SWAP QUEUE %'
SA_HPUX_11_Mu='%usr %sys %wio %idle,1 2 4 5 6 7,PROCESSOR ACTIVITY'
SA_HPUX_11_v='proc-sz inod-sz file-sz,1 2 5 7 9,STATUS OF PROCESS, INODE AND FILE TABLES PART 1:proc-ov inod-ov file-ov,1 2 6 8 10,STATUS OF PROCESS, INODE AND FILE TABLES PART 2'
SA_HPUX_11_w='swpin/s swpot/s,1 2 3 5,NUMBER OF PROCESS SWAP IN/OUT:bswin/s bswot/s,1 2 4 6,NUMBER OF 512-BYTE UNITS TRANSFERRED FOR SWAP IN/OUT:pswch/s,1 2 7,SYSTEM SWITCHING ACTIVITY'
SA_HPUX_11_y='rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_HPUX_11_SPECIAL='d Mq Mu'

# HP-UX 11.23-----------------------------------------------------------------------------------
SA_HPUX_23='a b c d Sm Mq Mu v w y'
SA_HPUX_23_a='iget/s namei/s dirbk/s,1 2 3 4 5,USE OF FILE ACCESS SYSTEM ROUTINES'
SA_HPUX_23_b='bread/s bwrit/s lread/s lwrit/s pread/s pwrit/s,1 2 3 4 5 6 9 10,BUFFER ACTIVITY PART 1:%rcache %wcache,1 2 7 8,BUFFER ACTIVITY PART 2'
SA_HPUX_23_c='rchar/s wchar/s,1 2 8 9,NUMBER OF CHARACTERS TRANSFERRED BY R/W SYSTEM CALLS:scall/s,1 2 3,NUMBER OF SYSTEM CALLS:sread/s swrit/s fork/s exec/s,1 2 4 5 6 7,R/W FORK AND EXEC SYSTEM CALLS'
SA_HPUX_23_d='r+w/s blks/s,1 2 6 7,NUMBER OF TRANSFERS:avque,1 2 5,NUMBER OF REQUESTS:avwait avserv,1 2 8 9,SERVICE AND WAIT TIMEi:%busy,1 2 4,BUSY TIME'
SA_HPUX_23_Sm='msg/s sema/s select/s,1 2 3 4 5,NUMBER OF SYSTEM V CALLS'
SA_HPUX_23_Mq='runq-sz swpq-sz,1 2 4 6,RUN AND SWAP QUEUE:%runocc %swpocc,1 2 5 7,RUN AND SWAP QUEUE %'
SA_HPUX_23_Mu='%usr %sys %wio %idle,1 2 4 5 6 7,PROCESSOR ACTIVITY'
SA_HPUX_23_v='proc-sz inod-sz file-sz,1 2 5 7 9,STATUS OF PROCESS, INODE AND FILE TABLES PART 1:proc-ov inod-ov file-ov,1 2 6 8 10,STATUS OF PROCESS, INODE AND FILE TABLES PART 2'
SA_HPUX_23_w='swpin/s swpot/s,1 2 3 5,NUMBER OF PROCESS SWAP IN/OUT:bswin/s bswot/s,1 2 4 6,NUMBER OF 512-BYTE UNITS TRANSFERRED FOR SWAP IN/OUT:pswch/s,1 2 7,SYSTEM SWITCHING ACTIVITY'
SA_HPUX_23_y='rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_HPUX_23_SPECIAL='d Mq Mu'

# HP-UX 11.31-----------------------------------------------------------------------------------
SA_HPUX_31='a b c Rd H L Sm Mq Mu v w y'
SA_HPUX_31_a='iget/s namei/s dirbk/s,1 2 3 4 5,USE OF FILE ACCESS SYSTEM ROUTINES'
SA_HPUX_31_b='bread/s bwrit/s lread/s lwrit/s pread/s pwrit/s,1 2 3 4 5 6 9 10,BUFFER ACTIVITY PART 1:%rcache %wcache,1 2 7 8,BUFFER ACTIVITY PART 2'
SA_HPUX_31_c='rchar/s wchar/s,1 2 8 9,NUMBER OF CHARACTERS TRANSFERRED BY R/W SYSTEM CALLS:scall/s,1 2 3,NUMBER OF SYSTEM CALLS:sread/s swrit/s fork/s exec/s,1 2 4 5 6 7,R/W FORK AND EXEC SYSTEM CALLS'
SA_HPUX_31_Rd='r/s w/s blks/s,1 2 6 7 8,NUMBER OF TRANSFERS:avque,1 2 5,NUMBER OF REQUESTS:avwait avserv,1 2 9 10,SERVICE AND WAIT TIME:%busy,1 2 4,BUSY TIME'
SA_HPUX_31_H='t-put read write,1 2 5 9 10,NUMBER OF BYTES TRANSFERRED:IO/s r/s w/s,1 2 6 7 8,NUMBER OF DATA TRANSFERS:avque,1 2 11,AVERAGE NUMBER OF REQUESTS:avwait avserv,1 2 12 13,AVERAGE WAIT AND SERVICE TIME:%util,1 2 4,UTILIZATION PERCENTAGE'
SA_HPUX_31_L='r/s w/s,1 2 6 7,NUMBER OF READ AND WRITES:blks/s,1 2 8,NUMBER OF BYTES TRANSFERRED:avwait avserv,1 2 9 10,SERVICE AND WAIT TIME:avque,1 2 5,AVERAGE NUMBER OF REQUESTS:%busy,1 2 4,BUSY TIME WHILE SERVICING'
SA_HPUX_31_Sm='msg/s sema/s select/s,1 2 3 4 5,NUMBER OF SYSTEM V CALLS'
SA_HPUX_31_Mq='runq-sz swpq-sz,1 2 4 6,RUN AND SWAP QUEUE:%runocc %swpocc,1 2 5 7,RUN AND SWAP QUEUE %'
SA_HPUX_31_Mu='%usr %sys %wio %idle,1 2 4 5 6 7,PROCESSOR ACTIVITY'
SA_HPUX_31_v='proc-sz inod-sz file-sz,1 2 5 7 9,STATUS OF PROCESS, INODE AND FILE TABLES PART 1:proc-ov inod-ov file-ov,1 2 6 8 10,STATUS OF PROCESS, INODE AND FILE TABLES PART 2'
SA_HPUX_31_w='swpin/s swpot/s,1 2 3 5,NUMBER OF PROCESS SWAP IN/OUT:bswin/s bswot/s,1 2 4 6,NUMBER OF 512-BYTE UNITS TRANSFERRED FOR SWAP IN/OUT:pswch/s,1 2 7,SYSTEM SWITCHING ACTIVITY'
SA_HPUX_31_y='rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_HPUX_31_SPECIAL='Rd H L Mq Mu'

# SunOS 9---------------------------------------------------------------------------------------
SA_SunOS_9='a b c d g k m p q u v w y'
SA_SunOS_9_a='iget/s namei/s dirbk/s,1 2 3 4 5,USE OF FILE ACCESS SYSTEM ROUTINES'
SA_SunOS_9_b='bread/s bwrit/s lread/s lwrit/s pread/s pwrit/s,1 2 3 4 5 6 9 10,BUFFER ACTIVITY PART 1:%rcache %wcache,1 2 7 8,BUFFER ACTIVITY PART 2'
SA_SunOS_9_c='rchar/s wchar/s,1 2 8 9,NUMBER OF CHARACTERS TRANSFERRED BY R/W SYSTEM CALLS:scall/s,1 2 3,NUMBER OF SYSTEM CALLS:sread/s swrit/s fork/s exec/s,1 2 4 5 6 7,R/W FORK AND EXEC SYSTEM CALLS'
SA_SunOS_9_d='r+w/s blks/s,1 2 6 7,NUMBER OF TRANSFERS:avque,1 2 5,NUMBER OF REQUESTS:avwait avserv,1 2 8 9,SERVICE AND WAIT TIMEi:%busy,1 2 4,BUSY TIME'
SA_SunOS_9_g='pgout/s ppgout/s pgfree/s pgscan/s,1 2 3 4 5 6,PAGING ACTIVITIES:%ufs_ipf,1 2 7,THE PERCENTAGE OF UFS INODES'
SA_SunOS_9_k='sml_mem alloc fail,1 2 3 4 5,KERNEL MEMORY ALLOCATION ACTIVITIES:lg_mem alloc fail,1 2 6 7 8,KMA FOR LARGE MEMORY POOL:ovsz_alloc fail,1 2 9 10,KMA FOR OVERSIZE REQUESTS'
SA_SunOS_9_m='msg/s sema/s,1 2 3 4,NUMBER OF SYSTEM V CALLS'
SA_SunOS_9_p='pgin/s,1 2 4,PAGE-IN REQUESTS:ppgin/s,1 2 5,PAGES PAGED-IN:atch/s pflt/s vflt/s slock/s,1 2 3 6 7 8,PAGE FAULTS'
SA_SunOS_9_q='runq-sz swpq-sz,1 2 3 5,RUN AND SWAP QUEUE:%runocc %swpocc,1 2 4 6,RUN AND SWAP QUEUE %'
SA_SunOS_9_u='%usr %sys %wio %idle,1 2 3 4 5 6,PROCESSOR ACTIVITY'
SA_SunOS_9_v='proc-sz inod-sz file-sz lock-sz,1 2 3 5 7 9,STATUS OF PROCESS, INODE AND FILE TABLES PART 1:proc-ov inod-ov file-ov,1 2 4 6 8,STATUS OF PROCESS, INODE AND FILE TABLES PART 2'
SA_SunOS_9_w='swpin/s swpot/s,1 2 3 5,NUMBER OF PROCESS SWAP IN/OUT:bswin/s bswot/s,1 2 4 6,NUMBER OF 512-BYTE UNITS TRANSFERRED FOR SWAP IN/OUT:pswch/s,1 2 7,SYSTEM SWITCHING ACTIVITY'
SA_SunOS_9_y='rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_SunOS_9_SPECIAL='d'

# SunOS 10--------------------------------------------------------------------------------------
SA_SunOS_10='a b c d g k m p q r u v w y'
SA_SunOS_10_a='iget/s namei/s dirbk/s,1 2 3 4 5,USE OF FILE ACCESS SYSTEM ROUTINES'
SA_SunOS_10_b='bread/s bwrit/s lread/s lwrit/s pread/s pwrit/s,1 2 3 4 5 6 9 10,BUFFER ACTIVITY PART 1:%rcache %wcache,1 2 7 8,BUFFER ACTIVITY PART 2'
SA_SunOS_10_c='rchar/s wchar/s,1 2 8 9,NUMBER OF CHARACTERS TRANSFERRED BY R/W SYSTEM CALLS:scall/s,1 2 3,NUMBER OF SYSTEM CALLS:sread/s swrit/s fork/s exec/s,1 2 4 5 6 7,R/W FORK AND EXEC SYSTEM CALLS'
SA_SunOS_10_d='r+w/s blks/s,1 2 6 7,NUMBER OF TRANSFERS:avque,1 2 5,NUMBER OF REQUESTS:avwait avserv,1 2 8 9,SERVICE AND WAIT TIMEi:%busy,1 2 4,BUSY TIME'
SA_SunOS_10_g='pgout/s ppgout/s pgfree/s pgscan/s,1 2 3 4 5 6,PAGING ACTIVITIES:%ufs_ipf,1 2 7,THE PERCENTAGE OF UFS INODES'
SA_SunOS_10_k='sml_mem alloc fail,1 2 3 4 5,KERNEL MEMORY ALLOCATION ACTIVITIES:lg_mem alloc fail,1 2 6 7 8,KMA FOR LARGE MEMORY POOL:ovsz_alloc fail,1 2 9 10,KMA FOR OVERSIZE REQUESTS'
SA_SunOS_10_m='msg/s sema/s,1 2 3 4,NUMBER OF SYSTEM V CALLS'
SA_SunOS_10_p='pgin/s,1 2 4,PAGE-IN REQUESTS:ppgin/s,1 2 5,PAGES PAGED-IN:atch/s pflt/s vflt/s slock/s,1 2 3 6 7 8,PAGE FAULTS'
SA_SunOS_10_q='runq-sz swpq-sz,1 2 3 5,RUN AND SWAP QUEUE:%runocc %swpocc,1 2 4 6,RUN AND SWAP QUEUE %'
SA_SunOS_10_r='freemem freeswap,1 2 3 4,UNUSED MEMORY AND SWAP'
SA_SunOS_10_u='%usr %sys %wio %idle,1 2 3 4 5 6,PROCESSOR ACTIVITY'
SA_SunOS_10_v='proc-sz inod-sz file-sz lock-sz,1 2 3 5 7 9,STATUS OF PROCESS, INODE AND FILE TABLES PART 1:proc-ov inod-ov file-ov,1 2 4 6 8,STATUS OF PROCESS, INODE AND FILE TABLES PART 2'
SA_SunOS_10_w='swpin/s swpot/s,1 2 3 5,NUMBER OF PROCESS SWAP IN/OUT:bswin/s bswot/s,1 2 4 6,NUMBER OF 512-BYTE UNITS TRANSFERRED FOR SWAP IN/OUT:pswch/s,1 2 7,SYSTEM SWITCHING ACTIVITY'
SA_SunOS_10_y='rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_SunOS_10_SPECIAL='d'

# SunOS 11--------------------------------------------------------------------------------------
SA_SunOS_11='a b c d g k m p q r u v w y'
SA_SunOS_11_a='iget/s namei/s dirbk/s,1 2 3 4 5,USE OF FILE ACCESS SYSTEM ROUTINES'
SA_SunOS_11_b='bread/s bwrit/s lread/s lwrit/s pread/s pwrit/s,1 2 3 4 5 6 9 10,BUFFER ACTIVITY PART 1:%rcache %wcache,1 2 7 8,BUFFER ACTIVITY PART 2'
SA_SunOS_11_c='rchar/s wchar/s,1 2 8 9,NUMBER OF CHARACTERS TRANSFERRED BY R/W SYSTEM CALLS:scall/s,1 2 3,NUMBER OF SYSTEM CALLS:sread/s swrit/s fork/s exec/s,1 2 4 5 6 7,R/W FORK AND EXEC SYSTEM CALLS'
SA_SunOS_11_d='r+w/s blks/s,1 2 6 7,NUMBER OF TRANSFERS:avque,1 2 5,NUMBER OF REQUESTS:avwait avserv,1 2 8 9,SERVICE AND WAIT TIMEi:%busy,1 2 4,BUSY TIME'
SA_SunOS_11_g='pgout/s ppgout/s pgfree/s pgscan/s,1 2 3 4 5 6,PAGING ACTIVITIES:%ufs_ipf,1 2 7,THE PERCENTAGE OF UFS INODES'
SA_SunOS_11_k='sml_mem alloc fail,1 2 3 4 5,KERNEL MEMORY ALLOCATION ACTIVITIES:lg_mem alloc fail,1 2 6 7 8,KMA FOR LARGE MEMORY POOL:ovsz_alloc fail,1 2 9 10,KMA FOR OVERSIZE REQUESTS'
SA_SunOS_11_m='msg/s sema/s,1 2 3 4,NUMBER OF SYSTEM V CALLS'
SA_SunOS_11_p='pgin/s,1 2 4,PAGE-IN REQUESTS:ppgin/s,1 2 5,PAGES PAGED-IN:atch/s pflt/s vflt/s slock/s,1 2 3 6 7 8,PAGE FAULTS'
SA_SunOS_11_q='runq-sz swpq-sz,1 2 3 5,RUN AND SWAP QUEUE:%runocc %swpocc,1 2 4 6,RUN AND SWAP QUEUE %'
SA_SunOS_11_r='freemem freeswap,1 2 3 4,UNUSED MEMORY AND SWAP'
SA_SunOS_11_u='%usr %sys %wio %idle,1 2 3 4 5 6,PROCESSOR ACTIVITY'
SA_SunOS_11_v='proc-sz inod-sz file-sz lock-sz,1 2 3 5 7 9,STATUS OF PROCESS, INODE AND FILE TABLES PART 1:proc-ov inod-ov file-ov,1 2 4 6 8,STATUS OF PROCESS, INODE AND FILE TABLES PART 2'
SA_SunOS_11_w='swpin/s swpot/s,1 2 3 5,NUMBER OF PROCESS SWAP IN/OUT:bswin/s bswot/s,1 2 4 6,NUMBER OF 512-BYTE UNITS TRANSFERRED FOR SWAP IN/OUT:pswch/s,1 2 7,SYSTEM SWITCHING ACTIVITY'
SA_SunOS_11_y='rawch/s canch/s outch/s rcvin/s xmtin/s mdmin/s,1 2 3 4 5 6 7 8,TTY DEVICE ACTIVITY'
SA_SunOS_11_SPECIAL='d'

# UBUNTU 18 -------------------------------------------------------------------------------------
SA_Ubuntu_18='b B d n_DEV n_EDEV n_NFS n_NFSD n_SOCK P_ALL q r H S v w W y'
SA_Ubuntu_18_b='tps rtps wtps,1 2 3 4 5,I/O TRANSACTION:bread/s bwrtn/s,1 2 6 7,I/O TRANSFER RATE'
SA_Ubuntu_18_B='pgpgin/s pgpgout/s,1 2 3 4,PAGING STATISTICS:fault/s majflt/s,1 2 5 6,PAGE FAULTS:pgfree/s pgscank/s pgscand/s pgsteal/s,1 2 7 8 9 10,PAGE OPERATIONS:%vmeff,1 2 11,EFFICIENCY OF PAGE RECLAIM'
SA_Ubuntu_18_d='tps,1 2 4,NUMBER OF KB TRANSFERS:rkB/s wkB/s,1 2 5 6,NUMBER OF KB r/w:areq-sz aqu-sz,1 2 7 8,I/O AVERAGE SIZE(KB) AND QUEUE LENGHT OF I/O REQUESTS:await,1 2 9,AVEARGE WAIT TIME,svctm,1 2 10,AVERAGE SERVICE TIME:%util,1 2 11,CPU PERCENTAGE of I/O'
SA_Ubuntu_18_H='kbhugfree kbhugused,1 2 3 4,HUGEPAGE UTILIZATION:%hugused,1 2 5,HUGEPAGE UTILIZATION %'
SA_Ubuntu_18_n_DEV='rxkB/s txkB/s,1 2 6 7,NETWORK I/O:rxpck/s txpck/s rxcmp/s txcmp/s rxmcst/s,1 2 4 5 8 9 10,NETWORK STATISTICS:%ifutil,1 2 11,UTILIZATION (%)'
SA_Ubuntu_18_n_EDEV='rxerr/s txerr/s coll/s rxdrop/s txdrop/s txcarr/s rxfram/s rxfifo/s txfifo/s,1 2 4 5 6 7 8 9 10 11 12,NETWORK ERROR STATISTICS'
SA_Ubuntu_18_n_NFS='read/s write/s,1 2 5 6,NUMBER OF RPC R/W:call/s retrans/s access/s getatt/s,1 2 3 4 7 8,NUMBER OF RPC REQUESTS AND ACCESSES'
SA_Ubuntu_18_n_NFSD='sread/s swrite/s,1 2 10 11,NUMBER OF RPC R/W:scall/s badcall/s saccess/s sgetatt/s,1 2 3 4 12 13,NUMBER OF RPC REQUESTS AND ACCESSES: packet/s udp/s tcp/s,1 2 5 6 7,NUMBER OF NETWORK PACKETS:hit/s miss/s,1 2 8 9,NUMBER OF REPLY CACHE HITS AND MISSES'
SA_Ubuntu_18_n_SOCK='totsck tcpsck udpsck rawsck ip-frag tcp-tw,1 2 3 4 5 6 7 8,NETWORK SOCKET STATISTICS'
SA_Ubuntu_18_P_ALL='%user %system %idle,1 2 4 6 9,PROCESSOR ACTIVITY:%nice %iowait %steal,1 2 5 7 8,PROCESSOR ACTIVITY DETAILS'
SA_Ubuntu_18_q='runq-sz,1 2 3,QUEUE LENGTH:plist-sz,1 2 4,NUMBER OF PROCESSES:blocked,1 2 8,NUMBER OF BLOCKED PROCESSES:ldavg-1 ldavg-5 ldavg-15,1 2 5 6 7,LOAD AVERAGE'
SA_Ubuntu_18_r='kbmemfree kbavail kbmemused kbbuffers kbcached kbcommit,1 2 3 4 5 7 8 9,MEMORY UTILIZATION:kbactive kbinact kbdirty,1 2 11 12 13,MEMORY UTILIZATION DETAILS:%memused %commit,1 2 6 10,MEMORY UTILIZATION %'
SA_Ubuntu_18_S='kbswpfree kbswpused kbswpcad,1 2 3 4 6,SWAP UTILIZATION:%swpused %swpcad,1 2 5 7,SWAP UTILIZATION %'
SA_Ubuntu_18_v='dentunusd,1 2 3,UNUSED CACHE ENTRIES:file-nr inode-nr,1 2 4 5,NUMBER OF FILE AND INODE HANDLERS:pty-nr,1 2 6,NUMBER OF PSEUDO-TERMINALS'
SA_Ubuntu_18_w='proc/s,1 2 3,PROCESS CREATION ACTIVITY:cswch/s,1 2 4,SYSTEM SWITCHING ACTIVITY'
SA_Ubuntu_18_W='pswpin/s pswpout/s,1 2 3 4,SWAPPING STATISTICS'
SA_Ubuntu_18_y='rcvin/s txmtin/s framerr/s prtyerr/s brk/s ovrun/s,1 2 4 5 6 7 8 9,TTY DEVICE ACTIVITY'
SA_Ubuntu_18_SPECIAL='d n_DEV n_EDEV P_ALL y'

# OS DEPENDENT SAR PARAMETERS -------------------------------------------------------------- END
################################################################################################


validip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}


# PLOTTING GRAPHICS ---------------------------------------------------------------------- START
################################################################################################
plot ()
{
SA_location="$1"
SC_OSNAME=`echo $SA_HOST | awk -F/ '{ print $2 }'`
SA_OPTIONS="SA_"$SC_OS
eval "SA_OPTIONS=\$$SA_OPTIONS"
SA_SDATE="$2"
SA_EDATE=`echo $3 | awk -F. '{ print $2"/"$3"/"$1 }'`
SA_EDATE=`date -d "$SA_EDATE +1 day" +%Y.%m.%d`
SA_PLOT="$SA_location/$SA_SDATE-$3/images.$$"
if [ ! -d $SA_location/$SA_SDATE-$3 ]; then
  mkdir -p $SA_PLOT
  for OPTION in $SA_OPTIONS; do
	SA_ITEMS="SA_"$SC_OS"_"$OPTION
	eval "SA_ITEMS=\$$SA_ITEMS"
	SA_ITEMcount=`echo $SA_ITEMS | awk -F: '{ print NF }'`
        for ((k=1;k<=$SA_ITEMcount;k+=1)); do
	  #for FILE in $( ls $SA_location/report/$OPTION.$k* 2> /dev/null | awk -F/ '{ print $NF }' ); do
	  for FILE in $( ls $SA_location/report/ 2> /dev/null | grep ^$OPTION.$k ); do
                echo "set xdata time" > $SA_LOC/PLOT.$$
                echo "set timefmt \"%Y.%m.%d\t%H%M\"" >> $SA_LOC/PLOT.$$
                echo "set xrange [\"$SA_SDATE\":\"$SA_EDATE\"]" >> $SA_LOC/PLOT.$$
                echo "set format x \"%m.%d\n%H:%M\"" >> $SA_LOC/PLOT.$$
                echo "set timefmt \"%Y.%m.%d %H:%M:%S\"" >> $SA_LOC/PLOT.$$
                echo "set key left below Right noreverse enhanced box linetype -2 linewidth 1.000 spacing 1 width 0 height 0 autotitles" >> $SA_LOC/PLOT.$$
                #echo "set style fill solid 1.000000 border" >> $SA_LOC/PLOT.$$
                #echo "set terminal png font helvetica 8 size 630, 350" >> $SA_LOC/PLOT.$$
                echo "set terminal png font \"helvetica,8\" size 630, 350" >> $SA_LOC/PLOT.$$
                #echo "set style fill solid 2.000000 border" >> $SA_LOC/PLOT.$$
                echo "set grid" >> $SA_LOC/PLOT.$$
                dev=`echo $FILE | awk -F-- '{ print $2 }'`
                title=`echo $SA_ITEMS | cut -f "$k" -d : | awk -F, '{ print $3 }'`
                if ! [ -z $dev ]; then
                        title=$title" - $dev"
                fi
	  	echo "---- Plotting $title..."
                echo "set title \"$title\"" >> $SA_LOC/PLOT.$$
                echo "set output \"$SA_PLOT/$FILE.png\"" >> $SA_LOC/PLOT.$$
                plot="plot "
                SA_parcount=`echo $SA_ITEMS | cut -f "$k" -d : | awk -F, '{ print $1 }' | awk '{ print NF }'`
                for ((j=1;j<=$SA_parcount;j+=1))
                do
                        SA_col=`echo "$j + 2" | bc`
                	SA_par=`echo $SA_ITEMS | cut -f "$k" -d : | awk -F, '{ print $1 }' | cut -f "$j" -d " "`
                        if [ $j -gt 1 ]; then
                                plot="$plot, "
                        fi
                        plot="$plot\"$SA_location/report/$FILE\" using 1:$SA_col with lines title \"$SA_par\""
                done
                echo $plot >> $SA_LOC/PLOT.$$
                gnuplot $SA_LOC/PLOT.$$ 2> /dev/null
                #rm -rf $SA_LOC/$$.restart
                rm -rf $SA_LOC/PLOT.$$
          done
	done
  done
  mv $SA_PLOT $SA_location/$SA_SDATE-$3/images
else
  echo "Report already generated before, terminating..."
fi
}

finddates ()
{
	SC_OS=`echo $SA_HOST | awk -F/ '{ print $1 }'`
	SA_LDATE=`cat $SA_LOC/$SA_HOST/report/b.1 | awk '{ print $1 }' | sort | uniq`
	if  [ ! -z $3 ]; then 
	  SA_SDATE="$3"
  	  if ( ! grep $SA_SDATE $SA_LOC/$SA_HOST/report/b.1 &> /dev/null ); then
		echo "No such date is available:$SA_SDATE"
		exit 1
  	  fi
	else
	  if [ "$1" = "-l" ]; then
	  	echo $SA_LDATE | tr ' ' '\n'
		exit 0
	  fi
	  echo $SA_LDATE | tr ' ' '\n' | awk '{print "  "NR,$0}' 
	  echo -n "Please select start date: "
	  read SA_SDATE
	  SA_SDATE=`echo $SA_LDATE | tr ' ' '\n' | awk '{print NR,$0}' | grep -w $SA_SDATE | awk '{ print $2 }'`
	  echo "Selected Start Date: "$SA_SDATE
	  echo ""
	  if ( ! grep $SA_SDATE $SA_LOC/$SA_HOST/report/b.1 &> /dev/null ); then
		echo "No such date is available:$SA_DATE"
		exit 1
	  fi
	fi


	if  [ ! -z $4 ]; then 
	  SA_EDATE="$4"
	  if ( ! grep $SA_EDATE $SA_LOC/$SA_HOST/report/b.1 &> /dev/null ); then
		echo "No such date is available:$SA_EDATE"
		exit 1
	  fi
	else
	  if [ $1 = "-l" ]; then
	  	echo $SA_LDATE | tr ' ' '\n' | sed '0,/'$SA_SDATE'/p' | sed '0,/'$SA_SDATE'/d'
		exit 0
	  fi
	  echo $SA_LDATE | tr ' ' '\n' | sed '0,/'$SA_SDATE'/p' | sed '0,/'$SA_SDATE'/d' | awk '{print "  "NR,$0}' 
	  echo -n "Please select end date: "
	  read SA_EDATE
	  echo ""
	  SA_EDATE=`echo $SA_LDATE | tr ' ' '\n' | sed '0,/'$SA_SDATE'/p' | sed '0,/'$SA_SDATE'/d' | awk '{print NR,$0}' | grep -w $SA_EDATE | awk '{ print $2 }'`
	  echo "Selected End Date: "$SA_EDATE
	  echo ""
	  if ( ! grep $SA_EDATE $SA_LOC/$SA_HOST/report/b.1 &> /dev/null ); then
		echo "No such end date is available..."
		exit 1
	  fi
	fi
	plot $2 $SA_SDATE $SA_EDATE
}

terminate ()
{
	echo -e "\033[33mUsage: ------------------------------------------------------- Display Commands" 
	echo -e "\033[36m       sar2html -d {sar2html report}                         - Display host name without extracting report file"
	echo -e "\033[36m       sar2html -o {sar2html report}                         - Display release without extracting report file"
	echo -e "\033[33m       ------------------------------------------------------- List Commands" 
	echo -e "\033[36m       sar2html -l [hostname] [start date] [end date]        - List existing hosts"
	echo -e "\033[36m       sar2html -r                                           - List existing hosts according to OS type"
	echo -e "\033[33m       ------------------------------------------------------- Report Commands" 
	echo -e "\033[36m       sar2html -a [host ip] [user name] [password]          - Capture report by connecting host"
	echo -e "\033[36m       sar2html -e {sar2html report}                         - Erase existing data of selected host"
	echo -e "\033[36m       sar2html -i {sar2html report} [start date] [end date] - Use new sar data and plot the content"
	echo -e "\033[36m       sar2html -m {sar2html report}                         - Only extract and merge new data"
	echo -e "\033[36m       sar2html -p [hostname] [start date] [end date]        - Plot using existing sar data"
	echo -e "\033[33m       ------------------------------------------------------- Management Commands" 
	echo -e "\033[36m       sar2html -c                                           - Configure sar2html"
	echo -e "\033[36m       sar2html -s                                           - Try configuring sar2html automatically"
	echo -e "\033[36m       sar2html -h                                           - Print this menu"
	exit $1
}

SA_ROOT=`pwd`
#SA_ROOT="/srv/www/htdocs"
SA_LOC="$SA_ROOT/sarDATA"
if [ ! -d $SA_ROOT ]; then
	echo "Error: Root directory of sar2html does not exist..."
	terminate 1
fi
if [ -z $1 ]; then
	terminate 0
elif [ $1 = "-h" ]; then
	terminate 0
elif [ $1 = "-c" ]; then
	echo -n "Please enter www user: "
	read S2_WWWU
	echo -n "Please enter www group: "
	read S2_WWWG
	mkdir -p $SA_LOC/uPLOAD/
	chown -R $S2_WWWU:$S2_WWWG $SA_LOC sarFILE sar2html index.php LICENSE
	echo "sar2html initialized. Now you may open index.php via your browser."
	exit 0

elif [ $1 = "-s" ]; then
	if [ ! -d $SA_LOC/uPLOAD ]; then
	  mkdir -p $SA_LOC/uPLOAD/
	  for webown in www http apache; do 
		if (grep $webown /etc/passwd &> /dev/null); then
			S2_WWWU=`grep $webown /etc/passwd | awk -F: '{ print $1 }'`
			S2_WWWG=`grep $webown /etc/group | awk -F: '{ print $1 }'`
			chown -R $S2_WWWU:$S2_WWWG $SA_LOC sarFILE sar2html index.php LICENSE
		fi
	  done
	 fi

# PLOT PERFORMANCE DATA USING EXISTING REPORT -------------------------------------------- START
################################################################################################
elif [ $1 = "-p" ] || [ $1 = "-l" ] || [ $1 = "-r" ] || [ $1 = "-e" ]; then
	if [ ! -z $2 ] && [ -d $SA_LOC/$2 ]; then 
		SA_HOST="$2"
	else
		cd $SA_LOC
		if ! ( ls -dlR */* &> /dev/null ); then
			echo "There is no defined host..."
			exit 1
		fi
		SA_LIST=`ls -dlR */* | grep -v uPLOAD | awk '{ print $9 }'`
		if [ $1 = "-l" ]; then
			if [ -z $2 ]; then 
				echo $SA_LIST | tr ' ' '\n'
				exit 0
			else
				SA_HOST="$2"
				if [ ! -d $SA_LOC/$SA_HOST ]; then
					echo "No such host is available..."
					exit 1
				fi
				finddates $1 $SA_LOC/$SA_HOST $3 $4
			fi
		fi
		if [ $1 = "-r" ]; then
			if [ -z $2 ]; then 
				echo "HPUX"
				echo $SA_LIST | tr ' ' '\n' | grep "HPUX" | awk '{ print "  "$1 }'
				echo "Linux"
				echo $SA_LIST | tr ' ' '\n' | grep -e "Redhat" -e "Suse" -e "Ubuntu" | awk '{ print "  "$1 }'
				echo "SunOS"
				echo $SA_LIST | tr ' ' '\n' | grep "SunOS" | awk '{ print "  "$1 }'
				exit 0
			else
				if ( echo $2 | grep -i "HPUX" > /dev/null ); then
					echo $SA_LIST | tr ' ' '\n' | grep "HPUX" | awk '{ print $1 }'
					exit 0
				elif ( echo $2 | grep -i "Linux" > /dev/null ); then
					echo $SA_LIST | tr ' ' '\n' | grep -e "Redhat" -e "Suse" -e "Ubuntu" | awk '{ print $1 }'
					exit 0
				elif ( echo $2 | grep -i "SunOS" > /dev/null ); then
					echo $SA_LIST | tr ' ' '\n' | grep "SunOS" | awk '{ print $1 }'
					exit 0
				else
					echo "This type of Operating System is not supported..."
					exit 0
				fi
				
			fi
		fi
		echo $SA_LIST | tr ' ' '\n' | grep -v upload | awk '{print "  "NR,$0}'
		echo -n "Please select the host: "
		read SA_HOST
		SA_HOST=`echo $SA_LIST | tr ' ' '\n' | grep -v upload | awk '{print NR,$0}' | grep -w $SA_HOST | awk '{ print $2 }'`
		echo "Selected Host: "$SA_HOST
		echo ""
	fi
	if [ ! -d $SA_LOC/$SA_HOST ]; then
		echo "No such host is available..."
		exit 1
	fi
	if [ $1 = "-e" ]; then
		if [ ! -z $3 ] && ([ $3 = "y" ] || [ $3 = "Y" ]); then		
			rm -rf $SA_LOC/$SA_HOST
		else
			echo -n "Are you sure to delete $SA_HOST [y/N]: "
			read SA_DECISION
			if [ $SA_DECISION = "y" ] || [ $SA_DECISION = "Y" ]; then
				rm -rf $SA_LOC/$SA_HOST
			fi
		fi
		exit 0
	fi
	if [ ! -z $3 ] && [ ! -z $4 ]; then finddates $1 $SA_LOC/$SA_HOST $3 $4
	elif [ ! -z $3 ] && [ -z $4 ]; then finddates $1 $SA_LOC/$SA_HOST $3
	elif [ -z $3 ] && [ -z $4 ]; then finddates $1 $SA_LOC/$SA_HOST; fi
################################################################################################
# PLOT PERFORMANCE DATA USING EXISTING REPORT ---------------------------------------------- END



# MERGE NEW REPORT WITH EXISTING REPORT AND PLOT ----------------------------------------- START
################################################################################################
elif [ $1 = "-i" ] || [ $1 = "-m" ] || [ $1 = "-d" ] || [ $1 = "-o" ]; then
  SA_HOST=`tar tzf $2 | tail -1 | awk -F/ '{ print $2"/"$3 }'`
  SC_OS=`echo $SA_HOST | awk -F/ '{ print $1 }'`
  if [ $1 = "-o" ]; then	
	if ( echo $SC_OS | grep -i -e "Redhat" -e "Suse" -e "Ubuntu" &> /dev/null ); then
		echo "LINUX"
	elif ( echo $SC_OS | grep -i "HPUX" &> /dev/null ); then
		echo "HPUX"
	elif ( echo $SC_OS | grep -i "SunOS" &> /dev/null ); then
		echo "SUNOS"
	else
		echo "Not supported release..."
		exit 1
	fi
	exit 0
  fi
  if [ $1 = "-d" ]; then	
	echo $SA_HOST
	exit 0
  fi
  mkdir -p $SA_LOC/sar2html.$$
  if ( tar zxf $2 -C $SA_LOC/sar2html.$$/ &> /dev/null ); then
	if [ ! -d $SA_LOC/sar2html.$$/sar2html ]; then
		rm -rf $SA_LOC/sar2html.$$
		echo "Error: Not valid sar2htm report..."
		terminate 1
	fi
	if [ -d $SA_LOC/$SA_HOST ]; then
		SA_REPFILES=`ls $SA_LOC/$SA_HOST/report`
		for FILE in $SA_REPFILES; do
		   if [ -f $SA_LOC/sar2html.$$/sar2html/$SA_HOST/report/$FILE ]; then # --> added by feistypenguin
			cat $SA_LOC/sar2html.$$/sar2html/$SA_HOST/report/$FILE >> $SA_LOC/$SA_HOST/report/$FILE
			cat $SA_LOC/$SA_HOST/report/$FILE | sort | uniq > $SA_LOC/$SA_HOST/report/$FILE.$$
			mv -f $SA_LOC/$SA_HOST/report/$FILE.$$ $SA_LOC/$SA_HOST/report/$FILE
		   fi
		done
	else
		mkdir -p $SA_LOC/$SC_OS 2> /dev/null
		mv $SA_LOC/sar2html.$$/sar2html/$SA_HOST $SA_LOC/$SC_OS/
	fi
	rm -rf $SA_LOC/sar2html.$$
	S2_WWWU=`ls -l sar2html | awk '{ print $3 }'`
	S2_WWWG=`ls -l sar2html | awk '{ print $4 }'`
	chown -R $S2_WWWU:$S2_WWWG $SA_LOC/$SC_OS
	if [ $1 = "-m" ]; then	exit 0; fi
	finddates $1 $SA_LOC/$SA_HOST 
  fi
################################################################################################
# MERGE NEW REPORT WITH EXISTING REPORT AND PLOT ------------------------------------------- END




# COLLECT REPORT by CONNECTING HOST ------------------------------------------------------ START
################################################################################################
elif [ $1 = "-a" ]; then
	NEW_HOSTUSER="root"
	if [ -z $2 ]; then
		echo -n "Please enter FQDN or IP Address of new host: "
		read NEW_HOST
	else
		NEW_HOST="$2"
	fi
	if ( ! validip $NEW_HOST ); then
		echo "Error: IP address is not valid."
		exit 1
	fi
	if [ -z $3 ]; then
		echo -n "Please enter user name for new host [root]: "
		read HOSTUSER
	else
		NEW_HOSTUSER="$3"
	fi
	if [ -z $4 ]; then
		echo -n "Please enter password for new host [root]: "
		read -s NEW_HOSTPASS
		if [ -z $NEW_HOSTPASS ]; then
			echo "Error: Password cannot be blank"
			exit 1
		fi
	else
		NEW_HOSTPASS="$4"
	fi
	if [ ! -z $HOSTUSER ]; then
		NEW_HOSTUSER="$HOSTUSER"
	fi
	echo ""
	echo "Copying sar2ascii to $NEW_HOST..."
	expect -c "
		set timeout 150
		spawn scp sarFILE/sar2ascii $NEW_HOSTUSER@$NEW_HOST:/usr/bin/
		expect \"*assword:*\" 
		send \"$NEW_HOSTPASS\r\"
		expect \"*# \"" &> /dev/null
	echo "Running sar2ascii on $NEW_HOST..."
	expect -c "
		set timeout 60
		spawn ssh $NEW_HOSTUSER@$NEW_HOST uname -s
		expect \"*assword:*\" 
		send \"$NEW_HOSTPASS\r\"
		expect \"*# \"" &> $SA_LOC/sar2ascii.$$
	if ( grep HP-UX $SA_LOC/sar2ascii.$$ &> /dev/null ); then
	   expect -c "
		set timeout 3000
		spawn ssh $NEW_HOSTUSER@$NEW_HOST sh /usr/bin/sar2ascii
		expect \"*assword:*\" 
		send \"$NEW_HOSTPASS\r\"
		expect \"*# \"" &> $SA_LOC/sar2ascii.$$
	else
	   expect -c "
		set timeout 3000
		spawn ssh $NEW_HOSTUSER@$NEW_HOST bash /usr/bin/sar2ascii
		expect \"*assword:*\" 
		send \"$NEW_HOSTPASS\r\"
		expect \"*# \"" &> $SA_LOC/sar2ascii.$$
	fi
	reportname=`cat $SA_LOC/sar2ascii.$$ | grep "Generating report file" | awk -F/ '{ print $3 }' | awk '{ print $1 }'`
	rm -rf $SA_LOC/sar2ascii.$$
	echo "Downloading report from $NEW_HOST..."
	expect -c "
		set timeout 300
		spawn scp $NEW_HOSTUSER@$NEW_HOST:/tmp/$reportname $SA_LOC/uPLOAD/
		expect \"*assword:*\" 
		send \"$NEW_HOSTPASS\r\"
		expect \"*# \"" &> /dev/null
	echo "Extracting report..."
	reportname=`echo $reportname | awk -F ".tar.gz" '{ print $1 }'`
	./sar2html -m $SA_LOC/uPLOAD/$reportname.tar.gz


################################################################################################
# COLLECT REPORT by CONNECTING HOST -------------------------------------------------------- END

else
	terminate 1
fi
